// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvwkhgyololbbhqaslco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2d2toZ3lvbG9sYmJocWFzbGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjY3NDEsImV4cCI6MjA2ODg0Mjc0MX0.TlBJOB08svFEfJM8dLwT4sfzZyFrG94q6bmEUVg2hfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});